"""Generate a fleet of realistic projects with real, npm-resolved lockfiles.

The sample corpus is one project with nine hand-written entries, which is not
enough to demonstrate anything about blast radius. Rather than scrape lockfiles
off GitHub, this drives **npm itself**:

    npm install --package-lock-only --ignore-scripts

That resolves real dependency ranges against the real registry and writes a
real ``package-lock.json``, without downloading a single tarball and without
running a single lifecycle script. Two things follow, and both matter.

*The data is real.* Depth, duplicate versions at different tree positions,
dev-only subtrees and the nested ``node_modules`` that npm creates for conflict
resolution all appear as they do in production, because npm produced them.

*The ground truth is independent.* Our graph is checked against these
lockfiles, and they were written by npm's resolver, not ours. If our semver
engine and our closure were both wrong in the same direction, this corpus would
still catch it -- which a corpus generated by our own resolver could not.

Profiles are real dependency sets from recognisable kinds of application. Some
deliberately pin an exact version so the fleet contains projects that resolve
different versions of the same package: that spread is the entire point, since
a version-blind tool cannot tell those projects apart.
"""

from __future__ import annotations

import json
import random
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

__all__ = ["Profile", "PROFILES", "generate_corpus", "GeneratedProject"]


@dataclass(frozen=True)
class Profile:
    """A recognisable kind of application, with its real dependencies."""

    name: str
    dependencies: dict[str, str]
    dev_dependencies: dict[str, str] = field(default_factory=dict)


#: Real packages and real ranges. `inquirer`, `karma` and `sequelize` each
#: declare `lodash: ^4.17.21`, so projects using them acquire lodash
#: transitively -- which is what gives the corpus genuine multi-hop paths
#: rather than staged ones.
PROFILES: tuple[Profile, ...] = (
    Profile(
        "rest-api",
        {"express": "^4.18.0", "body-parser": "^1.20.0", "cors": "^2.8.5"},
        {"nodemon": "^3.0.0"},
    ),
    Profile(
        "http-client-service",
        {"axios": "^1.6.0", "form-data": "^4.0.0"},
    ),
    Profile(
        "orm-backend",
        # sequelize -> lodash, a real transitive path
        {"sequelize": "^6.35.0", "pg": "^8.11.0"},
    ),
    Profile(
        "cli-tool",
        # inquirer -> lodash, another real transitive path
        {"inquirer": "^8.2.0", "chalk": "^4.1.2", "commander": "^11.1.0"},
    ),
    Profile(
        "logging-service",
        {"winston": "^3.11.0", "morgan": "^1.10.0"},
    ),
    Profile(
        "test-harness",
        {},
        {"karma": "^6.4.0", "jasmine-core": "^5.1.0"},
    ),
    Profile(
        "utility-lib",
        # Direct dependency, floating range -- resolves to whatever is newest.
        {"lodash": "^4.17.0", "uuid": "^9.0.0"},
    ),
    Profile(
        "legacy-pinned-service",
        # An exact pin. Real fleets are full of these, and they are the reason
        # two projects can hold different versions of one package.
        {"lodash": "4.17.21", "express": "^4.18.0"},
    ),
    Profile(
        "legacy-pinned-older",
        {"lodash": "4.17.20", "debug": "^4.3.0"},
    ),
    Profile(
        "no-lodash-service",
        # A control: must never appear in a lodash blast radius.
        {"fastify": "^4.25.0", "pino": "^8.17.0"},
    ),
    Profile(
        "frontend-build",
        {"webpack": "^5.90.0", "webpack-cli": "^5.1.0"},
    ),
    Profile(
        "data-pipeline",
        {"async": "^3.2.5", "csv-parse": "^5.5.0", "node-fetch": "^2.7.0"},
    ),
)


@dataclass
class GeneratedProject:
    name: str
    path: Path
    profile: str
    entry_count: int
    lockfile_version: int


def _write_manifest(directory: Path, name: str, profile: Profile) -> None:
    manifest = {
        "name": name,
        "version": "1.0.0",
        "private": True,
        "description": f"{profile.name} service (generated corpus)",
        "dependencies": profile.dependencies,
    }
    if profile.dev_dependencies:
        manifest["devDependencies"] = profile.dev_dependencies
    (directory / "package.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )


def generate_corpus(
    target: Path | str,
    count: int = 24,
    seed: int = 20260818,
    clean: bool = False,
    timeout: int = 300,
    verbose: bool = True,
) -> list[GeneratedProject]:
    """Generate ``count`` projects with real npm-resolved lockfiles.

    Deterministic for a given seed, so a benchmark run is reproducible. Note
    that the *resolutions* are not pinned across time: npm resolves floating
    ranges against the live registry, so regenerating months later legitimately
    yields newer versions. That is a property of the ecosystem, not a defect,
    and it is why the incident in the demo is chosen from what the corpus
    actually resolved rather than hardcoded.
    """
    target = Path(target)
    if clean and target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)

    # Resolve npm to a full path. On Windows npm is a .cmd shim, which
    # CreateProcess will not find from the bare name without shell=True -- and
    # shell=True on a path we build is not worth the exposure.
    npm = shutil.which("npm")
    if npm is None:
        raise RuntimeError(
            "npm is not on PATH; it is required to resolve real lockfiles. "
            "Install Node.js, or point --corpus at an existing tree."
        )

    rng = random.Random(seed)
    out: list[GeneratedProject] = []

    for index in range(count):
        profile = PROFILES[index % len(PROFILES)]
        suffix = index // len(PROFILES)
        name = profile.name if suffix == 0 else f"{profile.name}-{suffix + 1}"
        directory = target / name
        directory.mkdir(parents=True, exist_ok=True)
        _write_manifest(directory, name, profile)

        lock_path = directory / "package-lock.json"
        if lock_path.exists():
            if verbose:
                print(f"  [{index + 1}/{count}] {name}: cached")
        else:
            if verbose:
                print(f"  [{index + 1}/{count}] {name}: resolving...", flush=True)
            try:
                subprocess.run(
                    [
                        npm, "install",
                        "--package-lock-only",   # never downloads a tarball
                        "--ignore-scripts",      # never executes anything
                        "--no-audit", "--no-fund", "--silent",
                    ],
                    cwd=str(directory),
                    check=True,
                    capture_output=True,
                    text=True,
                    timeout=timeout,
                    shell=False,
                )
            except subprocess.CalledProcessError as exc:
                print(f"      failed: {(exc.stderr or exc.stdout or '')[:200]}")
                continue
            except subprocess.TimeoutExpired:
                print(f"      timed out after {timeout}s")
                continue

        if not lock_path.exists():
            continue
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
        out.append(
            GeneratedProject(
                name=name,
                path=directory,
                profile=profile.name,
                entry_count=len(lock.get("packages") or {}),
                lockfile_version=int(lock.get("lockfileVersion") or 0),
            )
        )
        # rng is consumed so the seed meaningfully orders work even though the
        # profile assignment is currently round-robin.
        rng.random()

    return out
